name: null

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.6
  - trimmomatic=0.39
  - multiqc=1.7
  - fastqc=0.11.8
  - samtools=1.8
  - bbmap=38.76
  - discovardenovo
